### ISSUE TITLE
CV_calc_no_empirical

### ISSUE THREAD

**Issue by cbroeckl** [weixiandeng/FAIMSpredictor#1]
Nice research!  i am trying this for the first time and having problems getting it to run:  

> library(FAIMSpredictor)
> CV_calc_no_empirical("AAAAAAAAAAAAA", 2)
 Connection successful!

R is connected to the H2O cluster: 
    H2O cluster uptime:         54 minutes 8 seconds 
    H2O cluster timezone:       America/Denver 
    H2O data parsing timezone:  UTC 
    H2O cluster version:        3.38.0.1 
    H2O cluster version age:    1 month and 26 days  
    H2O cluster name:           H2O_started_from_R_cbroeckl_vlk624 
    H2O cluster total nodes:    1 
    H2O cluster total memory:   4.88 GB 
    H2O cluster total cores:    8 
    H2O cluster allowed cores:  8 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          localhost 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    H2O Internal Security:      FALSE 
    R Version:                  R version 4.2.2 (2022-10-31 ucrt) 

  |                                                                                                             |   0%

water.exceptions.H2ONotFoundArgumentException: File C:/Users/cbroeckl/Documents/model1_no_empirical.zip does not exist

water.exceptions.H2ONotFoundArgumentException: File C:/Users/cbroeckl/Documents/model1_no_empirical.zip does not exist
	at water.persist.PersistNFS.importFiles(PersistNFS.java:127)
	at water.persist.PersistManager.importFiles(PersistManager.java:410)
	at hex.generic.Generic.importFile(Generic.java:148)
	at hex.generic.Generic.access$000(Generic.java:23)
	at hex.generic.Generic$MojoDelegatingModelDriver.compute2(Generic.java:90)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1677)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:976)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

Error: water.exceptions.H2ONotFoundArgumentException: File C:/Users/cbroeckl/Documents/model1_no_empirical.zip does not exist

> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] FAIMSpredictor_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        pillar_1.8.1      compiler_4.2.2    later_1.3.0       urlchecker_1.0.1  bitops_1.0-7     
 [7] Peptides_2.4.4    prettyunits_1.1.1 profvis_0.3.7     remotes_2.4.2     tools_4.2.2       digest_0.6.30    
[13] pkgbuild_1.3.1    pkgload_1.3.1     jsonlite_1.8.3    tibble_3.1.8      memoise_2.0.1     lifecycle_1.0.3  
[19] pkgconfig_2.0.3   rlang_1.0.6       shiny_1.7.3       cli_3.4.1         rstudioapi_0.14   curl_4.3.3       
[25] fastmap_1.1.0     dplyr_1.0.10      withr_2.5.0       stringr_1.4.1     generics_0.1.3    vctrs_0.5.0      
[31] fs_1.5.2          htmlwidgets_1.5.4 devtools_2.4.5    tidyselect_1.2.0  rprojroot_2.0.3   glue_1.6.2       
[37] R6_2.5.1          processx_3.8.0    fansi_1.0.3       h2o_3.38.0.1      sessioninfo_1.2.2 callr_3.7.3      
[43] purrr_0.3.5       magrittr_2.0.3    ps_1.7.2          promises_1.2.0.1  ellipsis_0.3.2    htmltools_0.5.3  
[49] usethis_2.1.6     mime_0.12         xtable_1.8-4      httpuv_1.6.6      utf8_1.2.2        stringi_1.7.8    
[55] miniUI_0.1.1.1    RCurl_1.98-1.9    cachem_1.0.6      crayon_1.5.2

**Comment by weixiandeng** [comment]
Thanks for reaching out, right now I'm having limited access to github, I will take a look at it ASAP.

**Comment by nprust** [comment]
I have the same error, so would be interested in the reason as well. 

Cheers,
Nadine

`library(FAIMSpredictor)
CV_calc_no_empirical("VQHIQLLQK",3)`

H2O is not running yet, starting it now...

Note:  In case of errors look at the following log files:
    C:\Users\LOCALA~1\AppData\Local\Temp\Rtmpmw3iPg\file44cc327b44ab/h2o_Proteomics_02_started_from_r.out
    C:\Users\LOCALA~1\AppData\Local\Temp\Rtmpmw3iPg\file44cc23c957f/h2o_Proteomics_02_started_from_r.err

java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

Starting H2O JVM and connecting:  Connection successful!

R is connected to the H2O cluster: 
    H2O cluster uptime:         3 seconds 855 milliseconds 
    H2O cluster timezone:       Europe/Berlin 
    H2O data parsing timezone:  UTC 
    H2O cluster version:        3.38.0.1 
    H2O cluster version age:    2 months and 2 days  
    H2O cluster name:           H2O_started_from_R_Proteomics-02_uft550 
    H2O cluster total nodes:    1 
    H2O cluster total memory:   29.97 GB 
    H2O cluster total cores:    48 
    H2O cluster allowed cores:  48 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          localhost 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    H2O Internal Security:      FALSE 
    R Version:                  R version 4.1.2 (2021-11-01) 

  |                                                                                                        |   0%

water.exceptions.H2ONotFoundArgumentException: File C:/Users/localadmin/Desktop/ProteomicsCenterEMC/model1_no_empirical.zip does not exist

water.exceptions.H2ONotFoundArgumentException: File C:/Users/localadmin/Desktop/ProteomicsCenterEMC/model1_no_empirical.zip does not exist
	at water.persist.PersistNFS.importFiles(PersistNFS.java:127)
	at water.persist.PersistManager.importFiles(PersistManager.java:410)
	at hex.generic.Generic.importFile(Generic.java:148)
	at hex.generic.Generic.access$000(Generic.java:23)
	at hex.generic.Generic$MojoDelegatingModelDriver.compute2(Generic.java:90)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1677)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:976)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

 Error: water.exceptions.H2ONotFoundArgumentException: File C:/Users/localadmin/Desktop/ProteomicsCenterEMC/model1_no_empirical.zip does not exist
11.
stop(m, call. = FALSE)
10.
doTryCatch(return(expr), name, parentenv, handler)
9.
tryCatchOne(expr, names, parentenv, handlers[[1L]])
8.
tryCatchList(expr, classes, parentenv, handlers)
7.
tryCatch({
jobPollSuccess <- FALSE
jobIsRecoverable <- FALSE
while (keepRunning) { ...
6.
.h2o.__waitOnJob(object@job_key, pollUpdates = ifelse(verbose, 
.h2o.pollModelUpdates, as.null))
5.
.h2o.getFutureModel(job, verbose = verbose)
4.
.h2o.modelJob("generic", parms, h2oRestApiVersion = 3, verbose = FALSE)
3.
h2o.generic(path = mojo_file_path, model_id)
2.
h2o::h2o.import_mojo(paste0(model_path, "/model1_no_empirical.zip"))

**Comment by weixiandeng** [comment]
I see what happened... 

So, it's because I didn't ask the package to download the two models automatically, I will figure out how to make it happen. 

For now, please download the two .zip files([model1_no_empirical.zip](https://github.com/weixiandeng/FAIMSpredictor/blob/main/model1_no_empirical.zip),[model2_empirical.zip](https://github.com/weixiandeng/FAIMSpredictor/blob/main/model2_empirical.zip)) to your working directory, then it should run through.
